// huawei-rtc-classroom/react/src/components/classroom/student-list/student-list.tsx
/*
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-10-21 11:11:44
 * @LastEditTime: 2021-10-21 13:08:12
 * @LastEditors: Yandong Hu
 * @Description: 
 */
import './student-list.scss';
import { useRecoilValue } from "recoil"
import { UserListState } from "../../../services/state-manager/classroom-state.service"

export const StudentList = () => {
    const userListState = useRecoilValue(UserListState);
    return (
        <div className="stu-lists">
            {userListState.lists.map((item, index) => 
            <div className="stu-item" key={item.userId}>
                <div className="stu-render" id="`user_${item.userId}`"></div>
                {!item.video && <div className="close">已关闭</div>} 
                <div className="stu-info-con">
                    <div className="name">{item.userName}</div>
                    <div className="userId">{item.userId}</div>
                </div>
            </div>
            )}
        </div>
    );
}

// huawei-rtc-classroom/src/components/classroom/StudentList.vue
<!--
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-08-04 15:35:56
 * @LastEditTime: 2021-08-13 13:43:00
 * @LastEditors: Yandong Hu
 * @Description:
-->
<template>
  <div class="stu-lists">
    <div class="stu-item" :key="item.userId" v-for="item in userListState">
      <div class="stu-render" :id="`user_${item.userId}`"></div>
      <div class="close" v-if="!item.video">已关闭</div>
      <div class="stu-info-con">
        <div class="name">{{ item.userName }}</div>
        <div class="userId">{{ item.userId }}</div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Options, Vue, Prop } from "vue-property-decorator";
import { UserListState } from "../../services/state-manager/classroom-state.service";

@Options({
  components: {},
})
export default class StudentList extends Vue {
  userListState = UserListState.lists;
  mounted() {
    console.log("StudentList mounted:!");
  }
  updated() {
    console.log("StudentList updated:!");
  }
}
</script>

<style lang="less" scoped>
.stu-lists {
  width: 100%;
  height: 108px;
  border-bottom: 1px solid #fff;
  display: flex;
  justify-content: center;
  .stu-item {
    width: 192px;
    height: 108px;
    position: relative;
  }
  .stu-render {
    width: 192px;
    height: 108px;
    background-color: #666;
    border: 1px solid #fff;
  }
  .close {
    position: absolute;
    bottom: 1px;
    left: 0;
    right: 0;
    top: 0;
    background-color: #000;
    display: flex;
    justify-content: center;
    align-items: center;
    color: #fff;
    font-size: 18px;
    font-weight: bold;
  }
  .stu-info-con {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    height: 22px;
    width: 190px;
    font-size: 14px;
    color: #fff;
    display: flex;
    justify-content: space-between;
    padding: 0 3px;
    margin: 0 1px;
    background-color: #eeeeee5e;
    line-height: 22px;
  }
}
</style>
