// huawei-rtc-classroom/react/src/components/classroom/main-boards/main-boards.tsx

/*
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-10-21 10:48:52
 * @LastEditTime: 2021-10-21 11:19:13
 * @LastEditors: Yandong Hu
 * @Description: 
 */
import { Button } from "antd"
import { RtcService } from "hrtc-sdk-services";
import { useRecoilState, useRecoilValue } from "recoil";
import { RemoteScreenShareListState, ScreenShareState } from "../../../services/state-manager/classroom-state.service";
import './main-boards.scss';
export const MainBoards = () => {
    const [screenShareState, setScreenShareState] = useRecoilState(ScreenShareState);
    const remoteScreenShareListValue = useRecoilValue(RemoteScreenShareListState);
    const stopScreenShare = () => {
        const stopState = RtcService().stopScreenShare();
        setScreenShareState({
            screenShareState: stopState == 0 ? false : true
        })
    }
    return(
        <div className="main-boards" id="board">
            {remoteScreenShareListValue.remoteShareList.length != 0 && 
                <div id="share-box" className="share-box"></div> } 
            {screenShareState.screenShareState &&
                <div className="share-msg">
                    <span>正在共享屏幕...</span>
                    <Button type="primary" size="small" onClick={stopScreenShare}>结束共享</Button>
                </div>
            }
        </div>
    )
}

// huawei-rtc-classroom/angular/src/app/components/classroom/main-boards/main-boards.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-main-boards',
  templateUrl: './main-boards.component.html',
  styleUrls: ['./main-boards.component.scss']
})
export class MainBoardsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<!--
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-10-26 10:11:32
 * @LastEditTime: 2021-10-26 10:36:35
 * @LastEditors: Yandong Hu
 * @Description:
-->
<div class="main-boards" id="board">
  <!-- <div v-if="shareState.remoteShareList.length != 0" id="share-box" class="share-box"></div>
  <div class="share-msg" v-if="shareState.screenShareState">
    <span>正在共享屏幕...</span>
    <el-button type="primary" size="small" @click="stopScreenShare()">结束共享</el-button>
  </div> -->
</div>
