// huawei-rtc-classroom/angular/src/app/pages/login/login.component.ts
/*
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-10-25 17:09:00
 * @LastEditTime: 2021-10-26 10:36:17
 * @LastEditors: Yandong Hu
 * @Description:
 */
import { Component, OnInit } from '@angular/core';
import { AudioService } from 'src/app/services/audio.services';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  roomName: string = '';
  userName: string = '';
  role: string = 'teacher';
  constructor(
    private audio: AudioService
  ) { }

  ngOnInit(): void {
    console.log('login componet init');
  }
  login() {
    console.log('login action', this.role, this.userName, this.roomName);
    this.audio.playInroomAudio();
  }
}

<!--
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-10-25 17:09:00
 * @LastEditTime: 2021-10-26 09:57:34
 * @LastEditors: Yandong Hu
 * @Description:
-->
<div class="login-box">
  <p>登录</p>
  <input nz-input placeholder="请输入教室名" [(ngModel)]="roomName" />
  <input nz-input placeholder="请输入姓名" [(ngModel)]="userName" />
  <div class="role">
    <nz-radio-group [(ngModel)]="role">
      <label nz-radio nzValue="teacher">老师</label>
      <label nz-radio nzValue="student">学生</label>
      <label nz-radio nzValue="audience">访客</label>
    </nz-radio-group>
  </div>
  <button nz-button nzType="primary" (click)="login()">进入教室</button>
</div>

// huawei-rtc-classroom/vue/src/pages/login/login.vue
<!--
 * @Author: Yandong Hu
 * @github: https://github.com/Mad-hu
 * @Date: 2021-09-10 13:12:01
 * @LastEditTime: 2021-10-20 09:36:11
 * @LastEditors: Yandong Hu
 * @Description:
-->
<template>
  <div class="login-box">
    <p>登录</p>
    <el-input
      v-model="roomName"
      placeholder="请输入教室名"
      type="text"
    ></el-input>
    <el-input
      v-model="userName"
      placeholder="请输入姓名"
      type="text"
    ></el-input>
    <div class="role">
      <el-radio v-model="role" label="teacher">老师</el-radio>
      <el-radio v-model="role" label="student">学生</el-radio>
      <el-radio v-model="role" label="audience">访客</el-radio>
    </div>
    <el-button type="primary" size="small" @click="login">进入教室</el-button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { messageFloatError } from "../../services/message/message-float.service";
import { RoomNameState } from "../../services/state-manager/classroom-state.service";
import { UserInfoState, UserRole } from "../../services/state-manager/user-state.service";
import { loadingShow } from "../../services/loading.service";

export default defineComponent({
  name: "Login",
  data() {
    return {
      roomName: "",
      userName: "",
      role: UserRole.teacher,
    };
  },
  computed: {},
  methods: {
    login() {
      try {
        if (this.roomName == "" || this.userName == "") {
          messageFloatError("用户或教室不能为空");
          return;
        }
        loadingShow("loading...");
        RoomNameState.roomName = this.roomName;
        const userId = parseInt((Math.random() * 100000).toFixed(0));
        UserInfoState.userName = this.userName;
        UserInfoState.userId = userId;
        UserInfoState.role = this.role;
        console.log("UserInfoState:", UserInfoState);
        setTimeout(() => {
          this.$router.push("/classroom");
        }, 1000);
      } catch (error) {}
    },
  },
});
</script>

<style lang="less" scoped>
.el-radio {
  color: #fff;
}
a {
  color: #42b983;
}
.login-box {
  display: flex;
  width: 400px;
  height: 250px;
  margin: 150px auto 0;
  flex-direction: column;
  justify-content: space-between;
  color: #fff;
}
.role {
  color: #fff;
}
</style>
